# Generated by Django 3.0.7 on 2020-09-05 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestionarticles', '0001_initial'),
        ('gestionpersonnels', '0001_initial'),
        ('gestionclients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gestionarticles.Article')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gestionclients.Client')),
            ],
            options={
                'db_table': 'commande',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetailsCommande',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qtecommande', models.IntegerField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gestionarticles.Article')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gestioncommandes.Commande')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gestionpersonnels.Personnel')),
            ],
            options={
                'db_table': 'detailscommande',
                'managed': True,
            },
        ),
    ]
