# Generated by Django 3.0.7 on 2020-09-09 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpersonnels', '0003_auto_20200905_2048'),
        ('gestioncommandes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='article',
        ),
        migrations.RemoveField(
            model_name='detailscommande',
            name='personnel',
        ),
        migrations.AddField(
            model_name='commande',
            name='personnel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='gestionpersonnels.Personnel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commande',
            name='total_prix_ht',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commande',
            name='total_prix_ttc',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detailscommande',
            name='prix_ht',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detailscommande',
            name='prix_ttc',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
