# Generated by Django 3.0.7 on 2020-09-13 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpersonnels', '0003_auto_20200905_2048'),
        ('gestioncommandes', '0002_auto_20200909_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='personnel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestionpersonnels.Personnel'),
        ),
    ]
