# Generated by Django 5.0.2 on 2024-03-04 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarticles', '0003_remove_article_categorie_delete_categorie'),
        ('gestionclients', '0001_initial'),
        ('gestioncommandes', '0003_auto_20200913_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestionclients.client'),
        ),
        migrations.AlterField(
            model_name='detailscommande',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestionarticles.article'),
        ),
        migrations.AlterField(
            model_name='detailscommande',
            name='commande',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestioncommandes.commande'),
        ),
    ]
