# Generated by Django 3.0.7 on 2020-09-05 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestionfournisseurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'categorie',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=50)),
                ('quantite_stock', models.FloatField()),
                ('prix_unitaire', models.FloatField()),
                ('tva', models.FloatField()),
                ('ttc', models.FloatField()),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gestionarticles.Categorie')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gestionfournisseurs.Fournisseur')),
            ],
            options={
                'db_table': 'article',
                'managed': True,
            },
        ),
    ]
