# Generated by Django 5.0.1 on 2024-02-15 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarticles', '0002_remove_article_ttc'),
        ('gestionfournisseurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestionarticles.categorie'),
        ),
        migrations.AlterField(
            model_name='article',
            name='fournisseur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestionfournisseurs.fournisseur'),
        ),
    ]
