# Generated by Django 5.0.2 on 2024-03-04 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarticles', '0002_remove_article_ttc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='categorie',
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
    ]
