# Generated by Django 3.0.7 on 2020-09-05 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestioncommandes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('montant_total', models.FloatField()),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gestioncommandes.Commande')),
            ],
            options={
                'db_table': 'livraison',
                'managed': True,
            },
        ),
    ]
