# Generated by Django 5.0.1 on 2024-02-11 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioncommandes', '0003_auto_20200913_2223'),
        ('gestionlivraisons', '0001_initial'),
        ('gestionpersonnels', '0003_auto_20200905_2048'),
        ('gestionvehicules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='chauffeur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestionpersonnels.personnel'),
        ),
        migrations.AddField(
            model_name='livraison',
            name='vehicule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestionvehicules.vehicule'),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='commande',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestioncommandes.commande'),
        ),
    ]
