# Generated by Django 5.0.2 on 2024-03-04 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioncommandes', '0004_alter_commande_client_alter_detailscommande_article_and_more'),
        ('gestionlivraisons', '0001_initial'),
        ('gestionpersonnels', '0003_auto_20200905_2048'),
        ('gestionvehicules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='chauffeur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestionpersonnels.personnel'),
        ),
        migrations.AddField(
            model_name='livraison',
            name='vehicule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestionvehicules.vehicule'),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='commande',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestioncommandes.commande'),
        ),
    ]
