# Generated by Django 3.0.7 on 2020-09-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpersonnels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='password',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='pseudo',
        ),
        migrations.AddField(
            model_name='personnel',
            name='id_admin',
            field=models.BooleanField(default=False),
        ),
    ]
