# Generated by Django 5.0.1 on 2024-02-07 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestionpersonnels', '0003_auto_20200905_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('matricule', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gestionpersonnels.personnel')),
            ],
            options={
                'db_table': 'vehicule',
                'managed': True,
            },
        ),
    ]
